[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }
emmet-ls = { command = "emmet-ls", args = ["--stdio"] }
eslint-ls = {command = "vscode-eslint-language-server", args = ["--stdio"], config = { nodePath = "", quiet = false, rulesCustomizations = [], run = "onType", validate = "on", codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }, problems = { shortenToSingleLine = false }, workingDirectory = { mode = "auto" }, experimental = { useFlatConfig = true } } }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "tailwindcss-ls", "emmet-ls", "biome" ]
auto-format = true

[[language]]
name = "jsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "tailwindcss-ls", "emmet-ls", "biome" ]
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "svelte"
language-servers = [ { name = "svelteserver", except-features = [ "format" ] }, "tailwindcss-ls", "emmet-ls", "eslint-ls" ]
formatter = { command = 'prettier', args = ["--parser", "svelte", "--plugin", "prettier-plugin-svelte", "--plugin", "prettier-plugin-tailwindcss", "--stdin"] }
auto-format = true

[[language]]
name = "swift"
auto-format = true
